# Generated by Django 3.0.2 on 2020-01-18 17:39

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='site-terms')),
                ('name', models.TextField(max_length=255)),
                ('version_number', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('text', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, help_text="Provide users with some info about what's changed and why", null=True)),
                ('status', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(blank=True, help_text='Leave Null To Never Make Active', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Services',
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'default_related_name': 'terms_of_services',
            },
        ),
        migrations.CreateModel(
            name='UserTermsOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_at_moment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, help_text='User profile data at the moment of agreement sign.')),
                ('date_accepted', models.DateTimeField(auto_now_add=True, verbose_name='Date Accepted')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_terms', to='tos.TermsOfServices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Terms of Service',
                'verbose_name_plural': 'User Terms of Service',
                'get_latest_by': 'date_accepted',
                'default_related_name': 'user_terms',
            },
        ),
        migrations.AddField(
            model_name='termsofservices',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='terms_of_services', through='tos.UserTermsOfService', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usertermsofservice',
            constraint=models.UniqueConstraint(fields=('user', 'terms'), name='Unique user terms'),
        ),
    ]
