# Generated by Django 3.0.2 on 2020-01-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0002_auto_20200118_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'default_related_name': 'terms_of_services', 'get_latest_by': ('activation_date', 'version_number'), 'ordering': ['-created'], 'verbose_name': 'Terms of Service', 'verbose_name_plural': 'Terms of Services'},
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='activation_date',
            field=models.DateTimeField(help_text='When this TOS will be active'),
        ),
    ]
