# Generated by Django 3.0.2 on 2020-01-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0003_auto_20200118_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'default_related_name': 'terms_of_services', 'verbose_name': 'Terms of Service', 'verbose_name_plural': 'Terms of Services'},
        ),
    ]
