# Generated by Django 3.0.2 on 2020-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0004_auto_20200119_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='slug',
            field=models.SlugField(default='butter-tos'),
        ),
    ]
