# Generated by Django 3.0.2 on 2020-01-22 14:31

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0005_auto_20200120_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofservice',
            name='info',
            field=models.TextField(default=datetime.datetime(2020, 1, 22, 14, 30, 51, 634225, tzinfo=utc), help_text="Provide users with some info about what's changed and why"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, help_text='Main terms of services text'),
            preserve_default=False,
        ),
    ]
